name: animated_login
description: Animated Login for Flutter. You can welcome your users with this beautiful animated screen that gives functionality for both login and sign up.
version: 1.7.1
homepage: https://github.com/bahricanyesil/flutter-animated-login
repository: https://github.com/bahricanyesil/flutter-animated-login

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  animations: ^2.0.7
  async: ^2.11.0
  flutter:
    sdk: flutter
  provider: ^6.0.5
  url_launcher: ^6.1.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.0.0

flutter:
  uses-material-design: true