name: animated_login
description: Animated Login for Flutter. You can welcome your users with this beautiful animated screen that gives functionality for both login and sign up.
version: 1.5.4
homepage: https://github.com/bahricanyesil/flutter-animated-login
repository: https://github.com/bahricanyesil/flutter-animated-login

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.3
  animations: ^2.0.3
  async: ^2.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
